Task 1: Basic Python Programming (20 Marks)

1. Write a function `fibonacci(n)` that generates the first `n` numbers in the Fibonacci sequence and returns

In [ ]:
def fib(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]

    fib_seq = [0, 1]
    for i in range(2, n):
        value = fib_seq[-1] + fib_seq[-2]
        fib_seq.append(value)

    return fib_seq

In [ ]:
fib(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

2. Write a function `is_prime(num)` that checks if a given number is a prime number. Return `True` if the nu

In [ ]:
num = int(input("Enter the number to check Prime or not "))

if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            print(False)
            break
    else:
        print(True)

Enter the number to check Prime or not 50
False

Task 2: Data Manipulation with Pandas (30 Marks)

Using the dataset provided below, perform the following tasks. The dataset contains information about a

In [ ]:
import pandas as pd
data = {
 'Date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05'],
 'Sales': [200, 220, 210, 215, 225],
 'Region': ['North', 'South', 'East', 'West', 'North'],
 'Manager': ['John', 'Jane', 'Joe', 'Jake', 'John']
}
df = pd.DataFrame(data)

In [ ]:
df

         Date  Sales Region Manager
0  2024-01-01    200  North    John
1  2024-01-02    220  South    Jane
2  2024-01-03    210   East     Joe
3  2024-01-04    215   West    Jake
4  2024-01-05    225  North    John

1. Load the dataset into a pandas DataFrame and display its first 5 rows. (5 Marks)

In [ ]:
df.head()

         Date  Sales Region Manager
0  2024-01-01    200  North    John
1  2024-01-02    220  South    Jane
2  2024-01-03    210   East     Joe
3  2024-01-04    215   West    Jake
4  2024-01-05    225  North    John

2. Add a new column `Profit` which is 10% of the `Sales` column. (5 Marks)

In [ ]:
df["Profit "] = df["Sales"].apply(lambda x: x * 0.1)
df

         Date  Sales Region Manager  Profit
0  2024-01-01    200  North    John     20.0
1  2024-01-02    220  South    Jane     22.0
2  2024-01-03    210   East     Joe     21.0
3  2024-01-04    215   West    Jake     21.5
4  2024-01-05    225  North    John     22.5

3. Group the data by `Region` and calculate the total sales for each region. (10 Marks)

In [ ]:
df.groupby("Region")["Sales"].sum()

Region
East     210
North    425
South    220
West     215
Name: Sales, dtype: int64

4. Find the region with the highest average sales. (10 Marks)

In [ ]:
df.groupby("Region")["Sales"].mean().sort_values(ascending=False)

Region
South    220.0
West     215.0
North    212.5
East     210.0
Name: Sales, dtype: float64

Task 3: Data Loading and Manipulation from GitHub (10 Marks)

1. Load a CSV file from a GitHub repository into a pandas DataFrame. Use the following URL for the datas https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

In [ ]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

In [ ]:
df = pd.read_html(url)

ValueError: No tables found

In [119]:
df = pd.read_csv(url)

Display the first 5 rows of the DataFrame. (1 Mark)

In [120]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Display summary statistics of the DataFrame. (1 Mark)

In [121]:
print("summary statistics of the DataFrame is mentioned Below:- \n")
print("-"*60)
df.describe()

summary statistics of the DataFrame is mentioned Below:-

------------------------------------------------------------

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

3. Check for null values in the DataFrame and display the count of null values in each column. (1 Mark)

In [122]:
print("Null Value in this DataFrame is mentioned Below:- \n")
print("-"*50)

df.isnull().sum()

Null Value in this DataFrame is mentioned Below:-

--------------------------------------------------

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

4. Fill the null values in the 'Age' column with the mean age. (1 Mark)

In [123]:
df["Age"] =df["Age"].fillna(df["Age"].mean())

print("after filling null values in the 'Age' column with the mean age \n")
print("-"*60)
df.isnull().sum()

after filling null values in the 'Age' column with the mean age

------------------------------------------------------------

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

5. Drop the rows where 'Embarked' is null. (1 Mark)

In [125]:
df["Embarked"] = df["Embarked"].dropna()

In [126]:
print("After Droping the Row of 'Embarked'(Null Value) \n")
print("-"*60)
df.isnull().sum()

After Droping the Row of 'Embarked'(Null Value)

------------------------------------------------------------

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [127]:
df = df.dropna(subset = ["Embarked"])

In [128]:
print("After Droping the Row of 'Embarked'(Null Value) \n")
print("-"*60)
df.isnull().sum()

After Droping the Row of 'Embarked'(Null Value)

------------------------------------------------------------

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

6. Create a new column 'FamilySize' which is the sum of 'SibSp' and 'Parch'. (1 Mark)

In [129]:
df["FamilySize"] = df["SibSp"] + df["Parch"]

In [130]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

7. Convert the 'Sex' column to numerical values (male: 0, female: 1). (1 Mark)

In [131]:
male = 0
female = 1
df["Sex"] = df["Sex"].map({"male" : male,"female": female})

In [132]:
print("After Converting the 'Sex' column to numerical values \n")
print("-"*60)

pd.DataFrame(df["Sex"].head(10))

After Converting the 'Sex' column to numerical values

------------------------------------------------------------

   Sex
0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1

8. Group the data by 'Pclass' and calculate the average fare for each class. (1 Mark)

In [133]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.193516
2    20.662183
3    13.675550
Name: Fare, dtype: float64

9. Find the most common port of embarkation ('Embarked' column). (1 Mark)

In [135]:
df["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [136]:
df["Embarked"].nunique()

3

In [137]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

10. Create a pivot table that shows the survival rate ('Survived') for each combination of 'Sex' and 'Pclass'

```
# This is formatted as code
```

In [140]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.000000,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.000000,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,373450,8.0500,NaN,S,0
5,6,0,3,"Moran, Mr. James",0,29.699118,0,0,330877,8.4583,NaN,Q,0
6,7,0,1,"McCarthy, Mr. Timothy J",0,54.000000,0,0,17463,51.8625,E46,S,0
7,8,0,3,"Palsson, Master. Gosta Leonard",0,2.000000,3,1,349909,21.0750,NaN,S,4
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,27.000000,0,2,347742,11.1333,NaN,S,2
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",1,14.000000,1,0,237736,30.0708,NaN,C,1

In [148]:


print("Create a pivot table that shows the survival rate ('Survived') for each combination of 'Sex' and 'Pclass\n")
print("-"*60)


pivot = df.pivot_table(index="Sex", columns="Pclass", values="Survived", aggfunc="mean")
print(pivot)

Create a pivot table that shows the survival rate ('Survived') for each combination of 'Sex' and 'Pclass

------------------------------------------------------------
Pclass         1         2         3
Sex
0       0.368852  0.157407  0.135447
1       0.967391  0.921053  0.500000